# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-13 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('addition_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_addition_configs', to='usergroups.ActionConfig')),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='group_owners', to=settings.AUTH_USER_MODEL)),
                ('sharing_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_sharing_configs', to='usergroups.ActionConfig')),
            ],
        ),
    ]
