# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-25 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0001_initial'),
        ('contests', '0010_auto_20181205_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='contests',
            field=models.ManyToManyField(blank=True, related_name='usergroups', to='contests.Contest'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='usergroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='owners',
            field=models.ManyToManyField(related_name='owned_usergroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
