# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-11 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20200128_1451'),
        ('usergroups', '0002_usergroup_contests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usergroups.UserGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usergroupranking',
            unique_together=set([('contest', 'user_group')]),
        ),
    ]
