# Generated by Django 2.2.24 on 2021-06-20 18:06

from django.db import migrations
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('evalmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedjob',
            name='state',
            field=oioioi.base.fields.EnumField(default='QUEUED', max_length=64),
        ),
    ]
