# Generated by Django 5.2.12 on 2026-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalmgr', '0002_auto_20210620_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestqueuedjob',
            options={'verbose_name': 'Contest Queued Job', 'verbose_name_plural': 'Contest Queued Jobs'},
        ),
    ]
