# Generated by Django 3.2.16 on 2022-12-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
