# Generated by Django 2.2.24 on 2021-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancemodeinfo',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
