# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  apt_packages:
    - curl
    - libpq-dev
    - libdb-dev
  tools:
    python: "3.8"
  jobs:
    pre_create_environment:
    - echo "Command run at 'pre_create_environment' step"
    post_create_environment:
    - echo "Command run at 'post_create_environment' step"
    - python3 -m pip install --upgrade --no-cache-dir "setuptools<58.0.0"
    post_system_dependencies:
    - echo "Command run at 'post_system_dependencies' step"
    

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: rst/source/conf.py

python:
   install:
   - requirements: requirements.txt
   - requirements: rst/requirements.txt
