FROM oioioi
ARG oioioi_uid

# This directory will be mounted from host by docker-compose
RUN rm -r /sio2/oioioi

# Change uid and permissions
USER root
RUN usermod -u $oioioi_uid oioioi
RUN find /sio2/ ~oioioi ! -user oioioi -exec chown oioioi:oioioi {} \;
USER oioioi
