x-common-envs: &common-envs
 FILETRACKER_URL: 'http://web:9999'
 DATABASE_HOST: 'db'
 DATABASE_PORT: '5432'

services:
  db:
    image: library/postgres:12.2
    environment:
      POSTGRES_USER: "oioioi"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "oioioi"
    volumes:
      - postgress-data:/var/lib/postgresql/data
    stop_grace_period: 1m
  web:
    image: sio2project/oioioi:$OIOIOI_VERSION
    command: ["/sio2/oioioi/oioioi_init.sh"]
    environment:
      OIOIOI_DB_ENGINE: 'django.db.backends.postgresql'
      RABBITMQ_HOST: 'broker'
      RABBITMQ_PORT: '5672'
      RABBITMQ_USER: 'oioioi'
      RABBITMQ_PASSWORD: 'oioioi'
      FILETRACKER_LISTEN_ADDR: '0.0.0.0'
      FILETRACKER_LISTEN_PORT: '9999'
      <<: *common-envs
    ports:
      - "8000:8000"
    stop_grace_period: 3m
    depends_on:
      - db
      - broker
    volumes:
      - filetracker-data:/sio2/deployment/media
  worker:
    image: sio2project/oioioi:$OIOIOI_VERSION
    command: ["/sio2/oioioi/worker_init.sh"]
    environment:
      WEB_URL: "web:8000"
      <<: *common-envs
    stop_grace_period: 1m
    cap_add:
      - ALL
    depends_on:
      - db
  broker:
    image: library/rabbitmq:3.8
    environment:
      RABBITMQ_DEFAULT_USER: oioioi
      RABBITMQ_DEFAULT_PASS: oioioi
    stop_grace_period: 1m
volumes:
  postgress-data:
  filetracker-data:
