[tox]
envlist = py311
requires = tox>=4
          tox-uv>=1.0.0

[testenv]
runner = uv-venv-runner
uv_path = uv
setenv =
# Needed for filetracker's Berkeley DB
    YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION = 1
    PYTHONPATH = {toxinidir}:{env:PYTHONPATH:}
commands_pre =
    uv sync --no-install-workspace --group dev
commands = pytest {posargs}
