# Generated by Django 2.2.24 on 2021-06-20 18:06

from django.db import migrations
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_mail_sent_datamigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=oioioi.base.fields.EnumField(default='QUESTION', max_length=64, verbose_name='kind'),
        ),
    ]
