# Generated by Django 4.2.3 on 2023-07-04 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_auto_20210620_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='marked_read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_marked_read_set', to=settings.AUTH_USER_MODEL, verbose_name='marked read by'),
        ),
    ]
