# Generated by Django 5.2.14 on 2026-09-18 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0008_addquestionmessage_newsmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipients",
            ),
        ),
    ]
