# Generated by Django 4.2.13 on 2024-07-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20220328_1124'),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveTaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_processes', models.IntegerField(default=1, verbose_name="number of user's processes to run")),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
