# Generated by Django 4.2.16 on 2024-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomePageMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='message')),
                ('language', models.CharField(max_length=6, verbose_name='language code')),
            ],
            options={
                'verbose_name': 'welcome page message',
                'verbose_name_plural': 'welcome page messages',
            },
        ),
    ]
