# Generated by Django 3.2.18 on 2023-03-02 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_auto_20230302_1913'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'talent registration',
                'verbose_name_plural': 'talent registrations',
                'ordering': ['user__last_name'],
            },
        ),
    ]
