# Generated by Django 3.2.18 on 2023-03-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0002_talentregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentregistration',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Talent registration', 'verbose_name_plural': 'Talent registrations'},
        ),
        migrations.AlterField(
            model_name='talentregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user'),
        ),
    ]
