# Generated by Django 3.2.18 on 2023-03-10 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0003_auto_20230310_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentregistration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_registration', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
