# Generated by Django 4.2.16 on 2024-10-07 08:29

from django.db import migrations, models
import django.db.models.deletion
import oioioi.participants.fields
import oioioi.szkopul.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oi', '0007_alter_oiregistration_class_type_and_more'),
        ('participants', '0011_alter_onsiteregistration_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAPCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='birth date')),
                ('class_type', models.CharField(choices=[('1LO', 'pierwsza szkoły średniej'), ('2LO', 'druga szkoły średniej'), ('3LO', 'trzecia szkoły średniej'), ('4LO', 'czwarta szkoły średniej'), ('5LO', 'piąta szkoły średniej'), ('1G', 'pierwsza gimnazjum'), ('2G', 'druga gimnazjum'), ('3G', 'trzecia gimnazjum'), ('1SP', 'pierwsza szkoły podstawowej'), ('2SP', 'druga szkoły podstawowej'), ('3SP', 'trzecia szkoły podstawowej'), ('4SP', 'czwarta szkoły podstawowej'), ('5SP', 'piąta szkoły podstawowej'), ('6SP', 'szósta szkoły podstawowej'), ('7SP', 'siódma szkoły podstawowej'), ('8SP', 'ósma szkoły podstawowej')], max_length=7, verbose_name='class')),
                ('parent_consent', models.FileField(upload_to=oioioi.szkopul.models.make_consent_filename, verbose_name='Zdjęcie/skan formularza zgody rodziców w przypadku bycia niepełnoletnim')),
                ('participant', oioioi.participants.fields.OneToOneBothHandsCascadingParticipantField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='participants.participant')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oi.school', verbose_name='school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
