# Generated by Django 4.2.13 on 2024-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szkopul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcourseregistration',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='mapcourseregistration',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='mapcourseregistration',
            name='parent_consent',
        ),
        migrations.RemoveField(
            model_name='mapcourseregistration',
            name='school',
        ),
        migrations.AddField(
            model_name='mapcourseregistration',
            name='not_primaryschool',
            field=models.BooleanField(default=False, verbose_name='not primary school'),
        ),
    ]
