# Generated by Django 5.2.9 on 2025-12-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_join_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('teacher', 'Is a teacher'),), 'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(auto_now_add=True, verbose_name='join date'),
        ),
    ]
