# Generated by Django 4.2.6 on 2023-11-15 08:06

from django.db import migrations
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsconfig',
            name='teams_list_visible',
            field=oioioi.base.fields.EnumField(default='NO', max_length=64, verbose_name='teams list visibility'),
        ),
    ]
