# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0007_auto_20200524_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunconfig',
            name='memory_limit',
            field=models.IntegerField(verbose_name='memory limit (KiB)'),
        ),
        migrations.AlterField(
            model_name='testrunconfig',
            name='time_limit',
            field=models.IntegerField(verbose_name='time limit (ms)'),
        ),
    ]
