# Generated by Django 3.2.16 on 2022-12-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0008_auto_20201214_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunprogramsubmission',
            name='input_is_zip',
            field=models.BooleanField(default=False),
        ),
    ]
