# Generated by Django 5.2.12 on 2026-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0008_auto_20201214_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunreport',
            name='mem_used',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
