# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoresreveal', '0003_copy_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerevealconfig',
            name='problem',
        ),
        migrations.AlterField(
            model_name='scorerevealconfig',
            name='problem_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores_reveal_config', to='contests.ProblemInstance', verbose_name='problem instance'),
        ),
    ]
