# Generated by Django 2.2.24 on 2021-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoresreveal', '0004_auto_20200523_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerevealconfig',
            name='reveal_limit',
            field=models.IntegerField(blank=True, help_text='If empty, all submissions are revealed automatically.', null=True, verbose_name='reveal limit'),
        ),
    ]
