# Generated by Django 5.2.12 on 2026-06-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0025_merge_0017_submission_max_score_0024_roundstartdelay'),
        ('scoresreveal', '0005_auto_20211123_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerevealconfig',
            name='contest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores_reveal_config', to='contests.contest', verbose_name='contest'),
        ),
        migrations.AlterField(
            model_name='scorerevealconfig',
            name='problem_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores_reveal_config', to='contests.probleminstance', verbose_name='problem instance'),
        ),
        migrations.AlterField(
            model_name='scorerevealconfig',
            name='reveal_limit',
            field=models.IntegerField(blank=True, help_text='If empty, all submissions are revealed automatically. A value of 0 disables reveals.', null=True, verbose_name='reveal limit'),
        ),
    ]
