# Generated by Django 3.2.16 on 2022-12-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoresreveal', '0006_scorerevealcontestconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorerevealcontestconfig',
            options={'verbose_name': 'default score reveal config', 'verbose_name_plural': 'default score reveal configs'},
        ),
    ]
