# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0003_auto_20161214_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oiregistration',
            name='class_type',
            field=models.CharField(choices=[(b'1LO', b'pierwsza szko\xc5\x82y ponadgimnazjalnej'), (b'2LO', b'druga szko\xc5\x82y ponadgimnazjalnej'), (b'3LO', b'trzecia szko\xc5\x82y ponadgimnazjalnej'), (b'4LO', b'czwarta szko\xc5\x82y ponadgimnazjalnej'), (b'5LO', b'pi\xc4\x85ta szko\xc5\x82y ponadgimnazjalnej'), (b'1G', b'pierwsza gimnazjum'), (b'2G', b'druga gimnazjum'), (b'3G', b'trzecia gimnazjum'), (b'1SP', b'pierwsza szko\xc5\x82y podstawowej'), (b'2SP', b'druga szko\xc5\x82y podstawowej'), (b'3SP', b'trzecia szko\xc5\x82y podstawowej'), (b'4SP', b'czwarta szko\xc5\x82y podstawowej'), (b'5SP', b'pi\xc4\x85ta szko\xc5\x82y podstawowej'), (b'6SP', b'sz\xc3\xb3sta szko\xc5\x82y podstawowej'), (b'7SP', b'si\xc3\xb3dma szko\xc5\x82y podstawowej'), (b'8SP', b'\xc3\xb3sma szko\xc5\x82y podstawowej')], max_length=7, verbose_name='class'),
        ),
    ]
