# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0004_auto_20171012_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.CharField(choices=[('dolno\u015bl\u0105skie', 'dolno\u015bl\u0105skie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('\u0142\xf3dzkie', '\u0142\xf3dzkie'), ('ma\u0142opolskie', 'ma\u0142opolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('\u015bl\u0105skie', '\u015bl\u0105skie'), ('\u015bwi\u0119tokrzyskie', '\u015bwi\u0119tokrzyskie'), ('warmi\u0144sko-mazurskie', 'warmi\u0144sko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie'), ('zagranica', 'zagranica')], db_index=True, max_length=100, verbose_name='province'),
        ),
    ]
