# Generated by Django 2.2.24 on 2021-06-20 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0005_auto_20191209_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oiregistration',
            name='class_type',
            field=models.CharField(choices=[('1LO', 'pierwsza szkoły ponadgimnazjalnej'), ('2LO', 'druga szkoły ponadgimnazjalnej'), ('3LO', 'trzecia szkoły ponadgimnazjalnej'), ('4LO', 'czwarta szkoły ponadgimnazjalnej'), ('5LO', 'piąta szkoły ponadgimnazjalnej'), ('1G', 'pierwsza gimnazjum'), ('2G', 'druga gimnazjum'), ('3G', 'trzecia gimnazjum'), ('1SP', 'pierwsza szkoły podstawowej'), ('2SP', 'druga szkoły podstawowej'), ('3SP', 'trzecia szkoły podstawowej'), ('4SP', 'czwarta szkoły podstawowej'), ('5SP', 'piąta szkoły podstawowej'), ('6SP', 'szósta szkoły podstawowej'), ('7SP', 'siódma szkoły podstawowej'), ('8SP', 'ósma szkoły podstawowej')], max_length=7, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='oiregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('\\+?[0-9() -]{6,}', 'Invalid phone number')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='oiregistration',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{3}$', 'Enter a postal code in the format XX-XXX')], verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='oiregistration',
            name='t_shirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=7, verbose_name='t-shirt size'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('\\+?[0-9() -]{6,}', 'Invalid phone number')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{3}$', 'Enter a postal code in the format XX-XXX')], verbose_name='postal code'),
        ),
    ]
