# Generated by Django 5.1.7 on 2025-04-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0007_alter_oiregistration_class_type_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='school',
            new_name='oi_school_city_21f890_idx',
            old_fields=('city', 'is_active'),
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='oi_school_provinc_42dc90_idx',
            old_fields=('province', 'is_active'),
        ),
    ]
