# Generated by Django 4.2.16 on 2024-10-07 08:49

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0007_alter_oiregistration_class_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[oioioi.base.utils.validators.validate_whitespaces], verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='rspo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oi.schooltype'),
        ),
    ]
