# Generated by Django 5.2.14 on 2026-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0010_drop_legacy_region_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='oiregistration',
            name='data_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data confirmed at'),
        ),
    ]
