# Generated by Django 5.2.14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_alter_probleminstance_submissions_limit'),
        ('oi', '0011_oiregistration_data_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDataConfirmationSettings',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='oi_data_confirmation_settings', serialize=False, to='contests.contest', verbose_name='contest')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether finalists must confirm their personal data during an active trial round of this contest.', verbose_name='require personal data confirmation')),
                ('source_contest', models.ForeignKey(blank=True, help_text="Contest whose registration data is suggested to participants for confirmation. If left empty, each participant's most recently submitted registration is used.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contests.contest', verbose_name='prefill data from contest')),
            ],
            options={
                'verbose_name': 'data confirmation settings',
                'verbose_name_plural': 'data confirmation settings',
            },
        ),
    ]
