# Generated by Django 5.2.14 on 2026-07-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_alter_probleminstance_submissions_limit'),
        ('oi', '0012_oidataconfirmationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidataconfirmationsettings',
            name='source_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contests.contest', verbose_name='prefill data from contest'),
        ),
    ]
