# Generated by Django 5.2.14 on 2026-08-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0013_alter_oidataconfirmationsettings_source_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidataconfirmationsettings',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Whether finalists must confirm their personal data during an active trial round of this contest.', verbose_name='require personal data confirmation'),
        ),
    ]
