# Generated by Django 5.2.14

import django.db.models.deletion
from django.db import migrations, models


def move_data_confirmed_at_forward(apps, schema_editor):
    OIRegistration = apps.get_model('oi', 'OIRegistration')
    OIDataConfirmation = apps.get_model('oi', 'OIDataConfirmation')
    for reg in OIRegistration.objects.exclude(data_confirmed_at=None):
        OIDataConfirmation.objects.update_or_create(
            participant=reg.participant,
            defaults={'data_confirmed_at': reg.data_confirmed_at},
        )


def move_data_confirmed_at_backward(apps, schema_editor):
    OIRegistration = apps.get_model('oi', 'OIRegistration')
    OIDataConfirmation = apps.get_model('oi', 'OIDataConfirmation')
    for confirmation in OIDataConfirmation.objects.exclude(data_confirmed_at=None):
        OIRegistration.objects.filter(participant=confirmation.participant).update(
            data_confirmed_at=confirmation.data_confirmed_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_alter_onsiteregistration_participant_and_more'),
        ('oi', '0014_alter_oidataconfirmationsettings_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDataConfirmation',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='oi_data_confirmation', serialize=False, to='participants.participant')),
                ('data_confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(move_data_confirmed_at_forward, move_data_confirmed_at_backward),
        migrations.RemoveField(
            model_name='oiregistration',
            name='data_confirmed_at',
        ),
    ]
