# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_auto_20170516_1133'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='node',
            managers=[
            ],
        ),
    ]
