# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_auto_20170516_1133'),
    ]

    operations = [
        # Previously this migration was a migrations.AlterModelManagers,
        # but the _base_manager attribute was removed and this errors
        # on Django1.10
    ]
