# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-31 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_global_portals_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLanguageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=6, verbose_name='language code')),
                ('full_name', models.CharField(help_text='Shown in the navigation menu.', max_length=32, validators=[oioioi.base.utils.validators.validate_whitespaces], verbose_name='full name')),
                ('panel_code', models.TextField(blank=True, verbose_name='panel code')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='full_name',
            field=models.CharField(blank=True, help_text='Shown in the navigation menu.', max_length=32, null=True, validators=[oioioi.base.utils.validators.validate_whitespaces], verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='node',
            name='panel_code',
            field=models.TextField(blank=True, null=True, verbose_name='panel code'),
        ),
        migrations.AddField(
            model_name='nodelanguageversion',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_versions', to='portals.Node'),
        ),
    ]
