# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-31 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_node_content_to_nodelanguageversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='node',
            name='panel_code',
        ),
    ]
