# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-06 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_global_portals_add_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodelanguageversion',
            unique_together=set([('node', 'language')]),
        ),
    ]
