# Generated by Django 4.2.6 on 2023-11-15 08:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20220328_1124'),
        ('portals', '0010_alter_nodelanguageversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='problems_in_content',
            field=models.ManyToManyField(blank=True, related_name='portal_pages', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='node',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='short_name',
            field=models.CharField(help_text='Shown in the URL.', max_length=32, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9_-]+$'), "Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='link_name',
            field=models.CharField(help_text='Shown in the URL.', max_length=40, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9_-]+$'), "Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
