# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-04 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20181205_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingVisibilityConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', oioioi.base.fields.EnumField(default=b'AUTO', help_text='If set to Auto, the visibility is determined according to the type of the contest.', max_length=64, verbose_name='ranking visibility')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
            options={
                'verbose_name': 'ranking visibility config',
                'verbose_name_plural': 'ranking visibility configs',
            },
        ),
    ]
