# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-28 13:51
from __future__ import unicode_literals

from django.db import migrations
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_rankingvisibilityconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingvisibilityconfig',
            name='visible',
            field=oioioi.base.fields.EnumField(default=b'AUTO', help_text='If set to Auto, the visibility is determined according to the type of the contest.\nUntil the date of publication of the results, the ranking is visible only to administrators.', max_length=64, verbose_name='ranking visibility'),
        ),
    ]
