# Generated by Django 2.2.24 on 2021-06-20 18:06

import django.core.validators
from django.db import migrations, models
import oioioi.base.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20200128_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9_-]+$'), "Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contestpermission',
            name='permission',
            field=oioioi.base.fields.EnumField(default='contests.contest_admin', max_length=64, verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='needs_rejudge',
            field=models.BooleanField(default=False, verbose_name='needs rejudge'),
        ),
        migrations.AlterField(
            model_name='probleminstance',
            name='short_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9_-]+$'), "Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='problemstatementconfig',
            name='visible',
            field=oioioi.base.fields.EnumField(default='AUTO', help_text='If set to Auto, the visibility is determined according to the type of the contest.', max_length=64, verbose_name='statements visibility'),
        ),
        migrations.AlterField(
            model_name='rankingvisibilityconfig',
            name='visible',
            field=oioioi.base.fields.EnumField(default='AUTO', help_text='If set to Auto, the visibility is determined according to the type of the contest.\nUntil the date of publication of the results, the ranking is visible only to administrators.', max_length=64, verbose_name='ranking visibility'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='kind',
            field=oioioi.base.fields.EnumField(default='NORMAL', max_length=64, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=oioioi.base.fields.EnumField(default='?', max_length=64, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='submissionreport',
            name='kind',
            field=oioioi.base.fields.EnumField(default='FINAL', max_length=64),
        ),
        migrations.AlterField(
            model_name='submissionreport',
            name='status',
            field=oioioi.base.fields.EnumField(default='INACTIVE', max_length=64),
        ),
    ]
