# Generated by Django 2.2.24 on 2022-03-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20210620_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable_editor',
            field=models.BooleanField(default=False, verbose_name='enable editor'),
        ),
    ]
