# Generated by Django 3.2.18 on 2023-04-05 20:59

from django.db import migrations
from django.db.models import OuterRef, Subquery, F
import oioioi.contests.fields

def add_max_scores(apps, _schema_editor):
    ScoreReport = apps.get_model('contests', 'ScoreReport')
    SubmissionReport = apps.get_model('contests', 'SubmissionReport')
    Submission = apps.get_model('contests', 'Submission')
    score_reports = ScoreReport.objects.filter(submission_report_id=OuterRef('id')).values('max_score')[:1]
    submission_reports = SubmissionReport.objects.filter(submission_id=OuterRef('id')).annotate(
            max_score=Subquery(score_reports),
            ).values('max_score')[:1]
    qs = Submission.objects.all().annotate(
            new_max_score=Subquery(submission_reports),
        ).update(
            max_score=F('new_max_score'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_auto_20230302_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=oioioi.contests.fields.ScoreField(blank=True, max_length=255, null=True, verbose_name='max score'),
        ),
        migrations.RunPython(add_max_scores,),
    ]
