# Generated by Django 4.2.5 on 2023-11-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_registrationavailabilityconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'files message',
                'verbose_name_plural': 'files messages',
            },
        ),
        migrations.CreateModel(
            name='SubmissionsMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'submissions message',
                'verbose_name_plural': 'submissions messages',
            },
        ),
        migrations.CreateModel(
            name='SubmitMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'new submission message',
                'verbose_name_plural': 'new submission messages',
            },
        ),
    ]
