# Generated by Django 4.2.2 on 2023-06-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_registrationavailabilityconfig'),
        ('contests', '0016_submission_max_score'),
    ]

    operations = [
    ]
