# Generated by Django 3.2.18 on 2023-04-05 20:59
# add_max_scores added by hand.

from django.db import migrations
from django.db.models import OuterRef, Subquery, F
import oioioi.contests.fields

def add_max_scores(apps, _schema_editor):
    ScoreReport = apps.get_model('contests', 'ScoreReport')
    SubmissionReport = apps.get_model('contests', 'SubmissionReport')
    Submission = apps.get_model('contests', 'Submission')

    score_reports_query = ScoreReport.objects.filter(
        submission_report_id=OuterRef('id'),
    ).values('max_score')[:1]

    submission_reports_query = SubmissionReport.objects.filter(
        submission_id=OuterRef('id')
    ).annotate(
        max_score=Subquery(score_reports_query),
    ).values('max_score')[:1]

    Submission.objects.all().annotate(
        new_max_score=Subquery(submission_reports_query),
    ).update(
        max_score=F('new_max_score'),
    )


def noop(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_filesmessage_submissionsmessage_submitmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=oioioi.contests.fields.ScoreField(blank=True, max_length=255, null=True, verbose_name='max score'),
        ),
        migrations.RunPython(add_max_scores, reverse_code=noop),
    ]
