# Generated by Django 4.2.8 on 2023-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_filesmessage_submissionsmessage_submitmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='is archived'),
        ),
    ]
