# Generated by Django 4.2.13 on 2024-10-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_contest_show_contest_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'submission message',
                'verbose_name_plural': 'submission messages',
            },
        ),
    ]
