# Generated by Django 5.1.7 on 2025-04-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_submissionmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contestview',
            new_name='contests_co_user_id_9b1d73_idx',
            old_fields=('user', 'timestamp'),
        ),
        migrations.RenameIndex(
            model_name='submissionreport',
            new_name='contests_su_submiss_4331a6_idx',
            old_fields=('submission', 'creation_date'),
        ),
    ]
