# Generated by Django 4.2.19 on 2025-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_submissionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='school_year',
            field=models.CharField(default='', max_length=10, verbose_name='school year'),
        ),
    ]
