# Generated by Django 4.2.19 on 2025-03-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_contest_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='school_year',
            field=models.CharField(default='', max_length=10, verbose_name='school year'),
        ),
    ]
