# Generated by Django 4.2.20 on 2025-04-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_sync_indexes_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contestview',
            new_name='contests_co_user_id_9b1d73_idx',
            old_name='contests_contestview_user_id_timestamp_a0151775_idx',
        ),
        migrations.RenameIndex(
            model_name='submissionreport',
            new_name='contests_su_submiss_4331a6_idx',
            old_name='contests_submissionrepor_submission_id_creation_d_df45e5ee_idx',
        ),
    ]
