# Generated by Django 4.2.20 on 2025-06-08 15:53

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0021_sync_indexes_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitsVisibilityConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', oioioi.base.fields.EnumField(default='NO', help_text="Determines whether participants can see problems' time and memory limits", max_length=64, verbose_name='limits visibility')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
            ],
            options={
                'verbose_name': 'limits visibility config',
                'verbose_name_plural': 'limits visibility configs',
            },
        ),
    ]
