# Generated by Django 5.2.3 on 2025-07-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0022_limitsvisibilityconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminstance',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.round', verbose_name='round'),
        ),
    ]
