# Generated by Django 5.2.12 on 2026-04-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_submission_max_score'),
        ('contests', '0024_roundstartdelay'),
    ]

    operations = [
    ]
