# Generated by Django 5.2.12 on 2026-05-20 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0025_merge_0017_submission_max_score_0024_roundstartdelay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminstance',
            name='submissions_limit',
            field=models.IntegerField(default=10, help_text='Use 0 for unlimited submissions.', validators=[django.core.validators.MinValueValidator(0, 'Submissions limit must be a non-negative number.')], verbose_name='submissions limit'),
        ),
    ]
