# Generated by Django 5.2.14 on 2026-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_alter_probleminstance_submissions_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminstance',
            name='can_access_editorial',
            field=models.BooleanField(default=False, help_text='Determines whether participants can access the editorial for this problem.', verbose_name='can access editorial'),
        ),
    ]
