# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-17 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipauthsync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipauthsyncconfig',
            name='region_server_mysql_db',
        ),
        migrations.RemoveField(
            model_name='ipauthsyncconfig',
            name='region_server_mysql_pass',
        ),
        migrations.RemoveField(
            model_name='ipauthsyncconfig',
            name='region_server_mysql_user',
        ),
    ]
