# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20200128_1451'),
        ('disqualification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisqualificationsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='information displayed on dashboard for every disqualified participant')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disqualifications_config', to='contests.Contest')),
            ],
            options={
                'verbose_name': 'diqualifications configuration',
                'verbose_name_plural': 'disqualifications configurations',
            },
        ),
    ]
