# Generated by Django 3.2.16 on 2023-01-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_contest_enable_editor'),
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionScoreMultiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField(verbose_name='multiplier')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='contest')),
            ],
        )
    ]
