# Generated by Django 4.2.11 on 2024-11-25 22:02

from django.db import migrations, models
import django.db.models.deletion
import oioioi.participants.fields


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_alter_onsiteregistration_participant_and_more'),
        ('oi', '0008_schooltype_school_rspo_school_type'),
        ('mp', '0003_alter_mpregistration_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP2025Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='terms accepted')),
                ('birth_year', models.IntegerField(verbose_name='year of birth')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name="teacher's name")),
                ('participant', oioioi.participants.fields.OneToOneBothHandsCascadingParticipantField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='participants.participant')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oi.school', verbose_name='school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
