# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-16 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ascii_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
