# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-16 15:16
from __future__ import unicode_literals

from django.db import migrations
from unidecode import unidecode


def save_all_problems(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    for problem in Problem.objects.all():
        problem.ascii_name = unidecode(problem.name)
        problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_ascii_name'),
    ]

    operations = [
        migrations.RunPython(save_all_problems),
    ]
