# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-15 18:43
# ADJUSTED manually
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Case, When, Value


def is_public_to_visibility(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    db_alias = schema_editor.connection.alias
    Problem.objects.using(db_alias).all().update(
        visibility=Case(
            When(is_public=True, then=Value(b'PU')),  # Public
            default=Value(b'FR')  # Friends
        )
    )


def visibility_to_is_public(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    db_alias = schema_editor.connection.alias
    Problem.objects.using(db_alias).all().update(
        is_public=Case(
            When(visibility=b'PU', then=Value(True)),  # Public
            default=Value(False)  # Other, we lose distinction: Private, Friends
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_newtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='visibility',
            field=models.CharField(choices=[(b'PU', b'Public'), (b'FR', b'Friends'), (b'PR', b'Private')], default=b'FR', max_length=2, verbose_name='visibility'),
        ),
        migrations.RunPython(is_public_to_visibility, visibility_to_is_public),
        migrations.RemoveField(
            model_name='problem',
            name='is_public',
        ),
    ]
