# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-15 18:43
# ADJUSTED manually
# Due to PostgreSQL transaction limitations, this migration was split into
# three parts:
# - part1 (this file) adds new visiblity field
# - part2 migrates data
# - part3 removes old is_public field
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Case, When, Value


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_newtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='visibility',
            field=models.CharField(choices=[('PU', 'Public'), ('FR', 'Friends'), ('PR', 'Private')], default='FR', max_length=2, verbose_name='visibility'),
        ),
    ]
