# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_algorithmtagproposal_difficultyproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempackage',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
    ]
