# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_auto_20201214_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmTagLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'en', b'English'), (b'pl', b'Polish')], max_length=2, verbose_name='language')),
                ('name', models.CharField(help_text='Human-readable name.', max_length=32, verbose_name='name translation')),
                ('algorithm_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='problems.AlgorithmTag')),
            ],
            options={
                'verbose_name': 'algorithm tag localization',
                'verbose_name_plural': 'algorithm tag localizations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='algorithmtaglocalization',
            unique_together=set([('algorithm_tag', 'language')]),
        ),
    ]
