# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-13 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_algorithm_tag_localization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithmtaglocalization',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='algorithmtag',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='name'),
        ),
    ]
