# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_algorithm_tag_algorithm_tag_localization_modify_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmtaglocalization',
            name='full_name',
            field=models.CharField(help_text='Human-readable name.', max_length=50, verbose_name='name translation'),
        ),
    ]
