# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-03 15:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_algorithm_tag_localization_modify_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyTagLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'en', b'English'), (b'pl', b'Polish')], max_length=2, verbose_name='language')),
                ('full_name', models.CharField(help_text='Human-readable name.', max_length=32, verbose_name='name translation')),
                ('difficulty_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='problems.DifficultyTag')),
            ],
            options={
                'verbose_name': 'difficulty tag localization',
                'verbose_name_plural': 'difficulty tag localizations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='difficultytaglocalization',
            unique_together=set([('difficulty_tag', 'language')]),
        ),
    ]
