# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-02 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0024_difficulty_tag_localization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyTagProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.DifficultyTag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'difficulty proposal',
                'verbose_name_plural': 'difficulty proposals',
            },
        ),
        migrations.RemoveField(
            model_name='difficultyproposal',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='difficultyproposal',
            name='user',
        ),
        migrations.DeleteModel(
            name='DifficultyProposal',
        ),
    ]
