# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-10 16:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_problem_alter_legacy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name.', max_length=255, verbose_name='name translation')),
                ('language', models.CharField(choices=[(b'en', b'English'), (b'pl', b'Polish')], max_length=2, verbose_name='language code')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='problems.Problem')),
            ],
            options={
                'verbose_name': 'problem name',
                'verbose_name_plural': 'problem names',
            },
        ),
        migrations.AlterUniqueTogether(
            name='problemname',
            unique_together=set([('problem', 'language')]),
        ),
    ]
