# Generated by Django 2.2.24 on 2021-06-20 18:06

import django.core.validators
from django.db import migrations, models
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_remove_tag_and_tagthrough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmtaglocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='difficultytaglocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origininfocategory',
            name='name',
            field=models.CharField(help_text="Type of information within this category. Short, searchable name consisting of only lowercase letters, numbers, and hyphens.<br>Examples: 'year', 'edition', 'stage', 'day'.", max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-z-]+$', 'Enter a valid name consisting only of lowercase letters, numbers, and hyphens.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='origininfocategorylocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origininfovalue',
            name='value',
            field=models.CharField(help_text="Short, searchable value consisting of only lowercase letters and numbers.<br>This will be displayed verbatim in the Problemset - it must be unique within its parent tag.<br>Examples: for year: '2011', but for round: 'r1' (just '1' for round would be ambiguous).", max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-z-]+$', 'Enter a valid name consisting only of lowercase letters, numbers, and hyphens.')], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='origininfovaluelocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origintag',
            name='name',
            field=models.CharField(help_text='Short, searchable name consisting only of lowercase letters, numbers, and hyphens.<br>This should refer to general origin, i.e. a particular contest, competition, programming camp, etc.<br>This will be displayed verbatim in the Problemset.', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-z-]+$', 'Enter a valid name consisting only of lowercase letters, numbers, and hyphens.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='origintaglocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='problemname',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language code'),
        ),
        migrations.AlterField(
            model_name='problempackage',
            name='status',
            field=oioioi.base.fields.EnumField(default='?', max_length=64, verbose_name='status'),
        ),
    ]
