# Generated by Django 4.2.16 on 2024-11-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20220328_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedDifficultyTagProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.difficultytag')),
            ],
            options={
                'verbose_name': 'aggregated difficulty tag proposal',
                'verbose_name_plural': 'aggregated difficulty tag proposals',
                'unique_together': {('problem', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='AggregatedAlgorithmTagProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.algorithmtag')),
            ],
            options={
                'verbose_name': 'aggregated algorithm tag proposal',
                'verbose_name_plural': 'aggregated algorithm tag proposals',
                'unique_together': {('problem', 'tag')},
            },
        ),
    ]
