# Generated by Django 4.2.13 on 2024-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20220328_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmtaglocalization',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'english')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='difficultytaglocalization',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'english')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origininfocategorylocalization',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'english')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origininfovaluelocalization',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'english')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origintaglocalization',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'english')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='problemname',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'english')], max_length=2, verbose_name='language code'),
        ),
    ]
