# Generated by Django 4.2.17 on 2024-12-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20220328_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficultytag',
            options={'ordering': ['pk'], 'verbose_name': 'difficulty tag', 'verbose_name_plural': 'difficulty tags'},
        ),
    ]
