# Generated by Django 4.2.16 on 2024-12-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('tagger', 'Can add and modify tags'), ('problems_db_admin', 'Can administer the problems database'), ('problem_admin', 'Can administer the problem')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
    ]
