# Generated by Django 4.2.16 on 2025-01-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_populate_aggregated_tag_proposals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('can_modify_tags', 'Can modify tags'), ('problems_db_admin', 'Can administer the problems database'), ('problem_admin', 'Can administer the problem')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
    ]
