# Generated by Django 4.2.16 on 2024-12-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0034_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('can_add_tags', 'Can add tags'), ('problems_db_admin', 'Can administer the problems database'), ('problem_admin', 'Can administer the problem')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
    ]
