# Generated by Django 4.2.16 on 2025-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0034_alter_problem_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aggregatedalgorithmtagproposal',
            index=models.Index(fields=['problem'], name='problems_ag_problem_e1cc67_idx'),
        ),
    ]
