# Generated by Django 4.2.16 on 2025-01-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_populate_aggregated_tag_proposals'),
        ('problems', '0036_alter_problem_options'),
    ]

    operations = [
    ]
