# Generated by Django 4.2.20 on 2025-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0037_alter_algorithmtaglocalization_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmtaglocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='difficultytaglocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origininfocategorylocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origininfovaluelocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='origintaglocalization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='problemname',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], max_length=2, verbose_name='language code'),
        ),
    ]
