# Generated by Django 5.2.3 on 2025-06-10 20:59

import django.db.models.deletion
import oioioi.filetracker.fields
import oioioi.problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0038_alter_algorithmtaglocalization_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemEditorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=6, null=True, verbose_name='language code')),
                ('content', oioioi.filetracker.fields.FileField(max_length=255, upload_to=oioioi.problems.models.make_problem_filename, verbose_name='content')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorials', to='problems.problem')),
            ],
            options={
                'verbose_name': 'problem editorial',
                'verbose_name_plural': 'problem editorials',
            },
        ),
    ]
