# Generated by Django 5.2.14 on 2026-07-20 22:35

import oioioi.filetracker.fields
import oioioi.problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0039_alter_algorithmtagproposal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemattachment',
            name='is_editorial',
            field=models.BooleanField(default=False, verbose_name='is editorial'),
        ),
        migrations.AddField(
            model_name='problemattachment',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Editorial publication date'),
        ),
        migrations.AddField(
            model_name='problemattachment',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='content',
            field=oioioi.filetracker.fields.FileField(blank=True, max_length=255, null=True, upload_to=oioioi.problems.models.make_problem_filename, verbose_name='content'),
        ),
    ]
