# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_filefield'),
        ('participants', '0007_auto_20160412_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAcceptedPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, null=True, verbose_name='text')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_accepted_phrase', to='contests.Contest')),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': "text asking participant to accept contest terms",
            },
        ),
    ]
