# Generated by Django 2.2.24 on 2021-06-20 18:06

import django.core.validators
from django.db import migrations, models
import oioioi.base.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_termsacceptedphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=oioioi.base.fields.EnumField(default='ACTIVE', max_length=64),
        ),
        migrations.AlterField(
            model_name='region',
            name='short_name',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9_-]+$'), "Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
