# Generated by Django 3.2.13 on 2022-04-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20210620_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsacceptedphrase',
            options={'verbose_name': 'text asking participant to accept contest terms', 'verbose_name_plural': 'text asking participant to accept contest terms'},
        ),
    ]
