# Generated by Django 4.2.4 on 2023-09-03 11:37

from django.db import migrations, models
import django.db.models.deletion
import oioioi.participants.fields


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_alter_termsacceptedphrase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsiteregistration',
            name='participant',
            field=oioioi.participants.fields.OneToOneBothHandsCascadingParticipantField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='participants.participant'),
        ),
        migrations.AlterField(
            model_name='onsiteregistration',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='openregistration',
            name='participant',
            field=oioioi.participants.fields.OneToOneBothHandsCascadingParticipantField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='participants.participant'),
        ),
        migrations.AlterField(
            model_name='testregistration',
            name='participant',
            field=oioioi.participants.fields.OneToOneBothHandsCascadingParticipantField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='participants.participant'),
        ),
    ]
