# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-26 18:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0008_filefield'),
        ('contests', '0009_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.Problem')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
            },
            bases=('problems.problem',),
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is answer correct')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'quiz answer',
                'verbose_name_plural': 'quiz answers',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='is multiple choice')),
                ('points', models.IntegerField(default=1, verbose_name='points')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz', verbose_name='quiz')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'quiz question',
                'verbose_name_plural': 'quiz questions',
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.Submission')),
            ],
            options={
                'verbose_name': 'quiz submission',
                'verbose_name_plural': 'quiz submissions',
            },
            bases=('contests.submission',),
        ),
        migrations.CreateModel(
            name='QuizSubmissionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False, verbose_name='is anwser selected')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.QuizAnswer', verbose_name='answer')),
                ('quiz_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizSubmission', verbose_name='quiz submission')),
            ],
            options={
                'verbose_name': 'quiz submission answer',
                'verbose_name_plural': 'quiz submission answers',
            },
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizQuestion', verbose_name='question'),
        ),
    ]
