# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.contests.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_filefield'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
                ('score', oioioi.contests.fields.ScoreField(max_length=255, verbose_name='score')),
                ('question_max_score', models.IntegerField(verbose_name='question max score')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.QuizQuestion', verbose_name='question')),
                ('submission_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.SubmissionReport', verbose_name='submission report')),
            ],
            options={
                'verbose_name': 'question report',
                'verbose_name_plural': 'question reports',
            },
        ),
    ]
