# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20180409_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
