# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields
import oioioi.contests.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20180409_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionreport',
            options={'verbose_name': 'Question report', 'verbose_name_plural': 'Question reports'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'ordering': ['order'], 'verbose_name': 'Quiz answer', 'verbose_name_plural': 'Quiz answers'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order'], 'verbose_name': 'Quiz question', 'verbose_name_plural': 'Quiz questions'},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'verbose_name': 'Quiz submission', 'verbose_name_plural': 'Quiz submissions'},
        ),
        migrations.AlterModelOptions(
            name='quizsubmissionanswer',
            options={'verbose_name': 'Quiz submission answer', 'verbose_name_plural': 'Quiz submission answers'},
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.QuizQuestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='question_max_score',
            field=models.IntegerField(verbose_name='Question max score'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='score',
            field=oioioi.contests.fields.ScoreField(max_length=255, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='status',
            field=oioioi.base.fields.EnumField(default=b'WA', max_length=64, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='submission_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.SubmissionReport', verbose_name='Submission report'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is answer correct'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizQuestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='is_multiple_choice',
            field=models.BooleanField(default=False, verbose_name='Is multiple choice'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizsubmissionanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.QuizAnswer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='quizsubmissionanswer',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Is answer selected'),
        ),
        migrations.AlterField(
            model_name='quizsubmissionanswer',
            name='quiz_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizSubmission', verbose_name='Quiz submission'),
        ),
    ]
