# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20180417_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('file', models.FileField(upload_to=b'', verbose_name='Image file')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizAnswer')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Quiz answer picture',
                'verbose_name_plural': 'Quiz answer pictures',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('file', models.FileField(upload_to=b'', verbose_name='Image file')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizQuestion')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Quiz question picture',
                'verbose_name_plural': 'Quiz question pictures',
            },
        ),
    ]
