# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizanswerpicture_quizquestionpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmissionTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(verbose_name='Text answer')),
            ],
            options={
                'verbose_name': 'Quiz submission text answer',
                'verbose_name_plural': 'Quiz submission text answers',
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='ignore_case',
            field=models.BooleanField(default=False, help_text='Only applies if answers are hidden.', verbose_name='Match user input case insensitively'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_text_input',
            field=models.BooleanField(default=False, help_text='Instead of listing answers, expect the contestant to type in their answer.', verbose_name='Hide answers'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='trim_whitespace',
            field=models.BooleanField(default=False, help_text='Only applies if answers are hidden.', verbose_name='Trim leading and trailing whitespace in user input'),
        ),
        migrations.AddField(
            model_name='quizsubmissiontextanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.QuizQuestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='quizsubmissiontextanswer',
            name='quiz_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizSubmission', verbose_name='Quiz submission'),
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmissiontextanswer',
            unique_together=set([('quiz_submission', 'question')]),
        ),
    ]
