# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20190902_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='trim_whitespace',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='ignore_case',
            field=models.BooleanField(default=True, help_text='Only applies if answers are hidden.', verbose_name='Match user input case insensitively'),
        ),
    ]
