# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-20 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20191120_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='ignore_case',
        ),
    ]
