# Generated by Django 2.2.24 on 2021-06-20 18:06

from django.db import migrations, models
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_quizquestion_ignore_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreport',
            name='status',
            field=oioioi.base.fields.EnumField(default='WA', max_length=64, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quizanswerpicture',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Image file'),
        ),
        migrations.AlterField(
            model_name='quizquestionpicture',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Image file'),
        ),
    ]
