# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-11 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsubmit', '0002_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsubmission',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='accepted by'),
        ),
    ]
