# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-08 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20160618_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='recalc_in_progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.RankingRecalc'),
        ),
    ]
