# Generated by Django 4.2.5 on 2023-11-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_filesmessage_submissionsmessage_submitmessage'),
        ('rankings', '0003_auto_20190308_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'ranking message',
                'verbose_name_plural': 'ranking messages',
            },
        ),
    ]
