# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryproblemdata',
            name='libname',
            field=models.CharField(help_text='Filename that the library should be given during compilation', max_length=30, verbose_name='libname'),
        ),
    ]
