# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_filefield'),
        ('programs', '0006_auto_20180417_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execuction_mode', oioioi.base.fields.EnumField(default=b'AUTO', help_text='If set to Auto, the execution mode is determined according to the type of the contest.', max_length=64, verbose_name='execution mode')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programs_config', to='contests.Contest')),
            ],
            options={
                'verbose_name': 'programs configuration',
                'verbose_name_plural': 'programs configurations',
            },
        ),
    ]
