# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-21 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20181205_1802'),
        ('problems', '0013_newtags'),
        ('programs', '0007_programsconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCompiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='language')),
                ('compiler', models.CharField(max_length=50, verbose_name='compiler')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest', verbose_name='contest')),
            ],
            options={
                'ordering': ('contest',),
                'verbose_name': 'contest compiler',
                'verbose_name_plural': 'contest compilers',
            },
        ),
        migrations.CreateModel(
            name='ProblemCompiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='language')),
                ('compiler', models.CharField(max_length=50, verbose_name='compiler')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem', verbose_name='problem')),
            ],
            options={
                'ordering': ('problem',),
                'verbose_name': 'problem compiler',
                'verbose_name_plural': 'problem compilers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='problemcompiler',
            unique_together=set([('problem', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='contestcompiler',
            unique_together=set([('contest', 'language')]),
        ),
    ]
