# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-17 22:41
from __future__ import unicode_literals

from django.db import migrations
import oioioi.contests.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_compilers2_part2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='max_score',
            field=oioioi.contests.fields.ScoreField(blank=True, max_length=255, null=True),
        )
    ]
