# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-18 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_manual_testreport_max_score_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='test_max_score',
        ),
    ]
