# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_algorithm_tag_localization'),
        ('programs', '0015_manual_execution_mode_sio2jail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAllowedLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem', verbose_name='problem')),
            ],
            options={
                'ordering': ('problem',),
                'verbose_name': 'problem allowed language',
                'verbose_name_plural': 'problem allowed languages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='problemallowedlanguage',
            unique_together=set([('problem', 'language')]),
        ),
    ]
