# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-25 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_add_allowed_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programsconfig',
            old_name='execuction_mode',
            new_name='execution_mode',
        ),
    ]
