# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 11:35
from __future__ import unicode_literals

from django.db import migrations
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20210425_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutgenstatus',
            name='status',
            field=oioioi.base.fields.EnumField(default='?', max_length=64),
        ),
    ]
