# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_alter_useroutgenstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageOverrideForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(null=True, validators=[oioioi.programs.models.validate_time_limit], verbose_name='time limit (ms)')),
                ('memory_limit', models.IntegerField(blank=True, null=True, validators=[oioioi.programs.models.validate_memory_limit], verbose_name='memory limit (KiB)')),
                ('language', models.CharField(max_length=30, verbose_name='language')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Test')),
            ],
            options={
                'verbose_name': 'test limit override',
                'verbose_name_plural': 'tests limit overrides',
                'ordering': ['test__order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='languageoverridefortest',
            unique_together=set([('test', 'language')]),
        ),
    ]
