# Generated by Django 4.2.16 on 2024-09-15 21:27

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_contest_show_contest_rules'),
        ('programs', '0019_add_limits_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsubmission',
            name='user_language_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='User language code'),
        ),
        migrations.CreateModel(
            name='CheckerFormatForProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', oioioi.base.fields.EnumField(max_length=64, verbose_name='format')),
                ('problem_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.probleminstance', verbose_name='problem instance')),
            ],
            options={
                'verbose_name': 'checker format for problem',
                'verbose_name_plural': 'checker formats for problems',
                'ordering': ('problem_instance',),
                'unique_together': {('problem_instance', 'format')},
            },
        ),
        migrations.CreateModel(
            name='CheckerFormatForContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', oioioi.base.fields.EnumField(help_text="Format of the checker output for this contest. Abbreviated describes the output difference, while Terse doesn't give any details.", max_length=64, verbose_name='format')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='contest')),
            ],
            options={
                'verbose_name': 'checker format for contest',
                'verbose_name_plural': 'checker formats for contests',
                'ordering': ('contest',),
                'unique_together': {('contest', 'format')},
            },
        ),
    ]
