# Generated by Django 4.2.16 on 2024-09-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_add_limits_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsubmission',
            name='user_language_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='User language code'),
        ),
    ]
