# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-15 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consents',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='terms accepted')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='first-party marketing consent')),
                ('partner_consent', models.BooleanField(default=False, verbose_name='third-party marketing consent')),
            ],
        ),
    ]
