# Generated by Django 3.1.14 on 2022-04-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('base', '0002_userpreferences'), ('base', '0003_auto_20220402_1557'), ('base', '0004_auto_20220402_1725'), ('base', '0005_auto_20220402_1725'), ('base', '0006_auto_20220402_1819'), ('base', '0007_auto_20220403_0924'), ('base', '0008_auto_20220403_0928')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='user')),
                ('language', models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('', 'None')], default='', max_length=2)),
            ],
        ),
    ]
