# Generated by Django 3.2.13 on 2022-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0003_auto_20220420_1236'), ('base', '0004_rename_preferred_language_userpreferences_language')]

    dependencies = [
        ('base', '0002_userpreferences_squashed_0008_auto_20220403_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='language',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='enable_editor',
            field=models.BooleanField(default=False, verbose_name='Używaj edytora kodu'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('', 'None')], default='', max_length=2, verbose_name='preferred_language'),
        ),
    ]
