# Generated by Django 4.2.13 on 2024-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_userpreferences_enable_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'english'), ('', 'None')], default='', max_length=2, verbose_name='preferred_language'),
        ),
    ]
