# Generated by Django 4.2.20 on 2025-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_userpreferences_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('', 'None')], default='', max_length=2, verbose_name='preferred_language'),
        ),
    ]
