# Generated by Django 4.2.16 on 2024-12-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
