# Generated by Django 5.2.14 on 2026-06-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_userpreferences_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="programming_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "C"),
                    ("C++", "C++"),
                    ("Pascal", "Pascal"),
                    ("Java", "Java"),
                    ("Python", "Python"),
                    ("", "None"),
                ],
                default="",
                max_length=64,
                verbose_name="preferred programming language",
            ),
        ),
    ]
