# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-08 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_user_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
