# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def migrate_category_order_default_value(apps, schema_editor):
    Category = apps.get_model("forum", "Category")
    Category.objects.all().update(order=F("id"))


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_auto_20190308_1931"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
        migrations.RunPython(
            migrate_category_order_default_value, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.IntegerField(verbose_name="order"),
        ),
        migrations.AlterUniqueTogether(
            name="category", unique_together=set([("forum", "order")]),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("order",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
