# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-23 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_post_report_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_reaction', oioioi.base.fields.EnumField(max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.Post', verbose_name='post')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='reactions_enabled',
            field=models.BooleanField(default=False, verbose_name='reactions enabled'),
        ),
    ]
