# Generated by Django 2.2.24 on 2021-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_post_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='report_reason',
            field=models.TextField(blank=True, default='', verbose_name='report_reason'),
        ),
    ]
