# Generated by Django 4.2.4 on 2023-09-03 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0009_auto_20210620_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
