# Generated by Django 4.2.5 on 2023-11-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_filesmessage_submissionsmessage_submitmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0009_auto_20210620_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'forum message',
                'verbose_name_plural': 'forum messages',
            },
        ),
        migrations.CreateModel(
            name='NewPostMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'new post message',
                'verbose_name_plural': 'new post messages',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
