# Generated by Django 4.2.5 on 2023-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_post_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='only_for_registered',
            field=models.BooleanField(default=True, verbose_name='allow only registered users to post on forum'),
        ),
    ]
