# Generated by Django 4.2.6 on 2023-12-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_forummessage_newpostmessage_alter_post_reported_by'),
        ('forum', '0011_forum_only_for_registered'),
    ]

    operations = [
    ]
