# Generated by Django 5.1.7 on 2025-04-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_merge_20231222_1900'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='forum_post_thread__54acb8_idx',
            old_fields=('thread', 'add_date'),
        ),
    ]
