# Generated by Django 4.2.16 on 2025-01-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_merge_20231222_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreaction',
            options={'ordering': ['-pk']},
        ),
    ]
