# Generated by Django 4.2.20 on 2025-04-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_sync_indexes_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='forum_post_thread__54acb8_idx',
            old_name='forum_post_thread_id_add_date_6d8ec21d_idx',
        ),
    ]
