# Generated by Django 4.2.11 on 2024-10-21 20:48

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalmessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmessage',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated'),
            preserve_default=False,
        ),
    ]
