# Generated by Django 4.2.6 on 2023-12-04 09:09

from django.db import migrations, models
import oioioi.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0003_alter_paregistration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paregistration',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='paregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='paregistration',
            name='postal_code',
            field=oioioi.base.fields.PostalCodeField(blank=True, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='paregistration',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=7, null=True, verbose_name='t-shirt size'),
        ),
    ]
